export const UI_ASSETS = {
  btnMatchLarge: "/assets/production/buttons/btn_match_large.png",
  btnTrainingLarge: "/assets/production/buttons/btn_training_large.png",
  btnPlayersLarge: "/assets/production/buttons/btn_players_large.png",
  btnScheduleLarge: "/assets/production/buttons/btn_schedule_large.png",
  btnItemSmall: "/assets/production/buttons/btn_item_small.png",
  btnScoutSmall: "/assets/production/buttons/btn_scout_small.png",
  btnDataSmall: "/assets/production/buttons/btn_data_small.png",
  btnSystemSmall: "/assets/production/buttons/btn_system_small.png",
  tabsPrimaryRow: "/assets/production/buttons/tabs_primary_row.png",
  btnConfirmCancelPair: "/assets/production/buttons/btn_confirm_cancel_pair.png",
  btnConfirmLarge: "/assets/production/buttons/btn_confirm_large.png",
  btnCancelLarge: "/assets/production/buttons/btn_cancel_large.png",
  controlCheckboxes: "/assets/production/buttons/control_checkboxes.png",
  controlTogglesSliders: "/assets/production/buttons/control_toggles_sliders.png",
  controlPaginationTabs: "/assets/production/buttons/control_pagination_tabs.png",
  badgesNotifications: "/assets/production/buttons/badges_notifications.png",
  mascotStanding: "/assets/production/mascots/mascot_standing.png",
  mascotPointing: "/assets/production/mascots/mascot_pointing.png",
  mascotClipboard: "/assets/production/mascots/mascot_clipboard.png",
  mascotCheering: "/assets/production/mascots/mascot_cheering.png",
  mascotSweating: "/assets/production/mascots/mascot_sweating.png",
  mascotFacesStrip: "/assets/production/mascots/mascot_faces_strip.png",
  mascotBadge: "/assets/production/mascots/mascot_badge.png",
  panelLargeBlueHeader: "/assets/production/panels/panel_large_blue_header.png",
  panelNoticeList: "/assets/production/panels/panel_notice_list.png",
  panelNoteMemo: "/assets/production/panels/panel_note_memo.png",
  panelGoalChecklist: "/assets/production/panels/panel_goal_checklist.png",
  panelStatusGroup: "/assets/production/panels/panel_status_group.png",
  dialogModalLarge: "/assets/production/panels/dialog_modal_large.png",
  dialogModalSmall: "/assets/production/panels/dialog_modal_small.png",
  dialogueBoxMascotLeft: "/assets/production/panels/dialogue_box_mascot_left.png",
  tutorialPopup: "/assets/production/panels/tutorial_popup.png",
  playerCardGold: "/assets/production/cards/player_card_gold.png",
  playerCardsSet: "/assets/production/cards/player_cards_set.png",
  rosterTableRows: "/assets/production/cards/roster_table_rows.png",
  scoreboardMain: "/assets/production/scoreboards/scoreboard_main.png",
  resultStamps: "/assets/production/scoreboards/result_stamps.png",
  trainingResultPanel: "/assets/production/scoreboards/training_result_panel.png",
  calendarMonth: "/assets/production/schedule/calendar_month.png",
  weeklyScheduleCards: "/assets/production/schedule/weekly_schedule_cards.png",
  locationTiles: "/assets/production/schedule/location_tiles.png",
  missionPanel: "/assets/production/schedule/mission_panel.png",
  rewardPopup: "/assets/production/schedule/reward_popup.png",
  saveSlots: "/assets/production/schedule/save_slots.png",
  baseballIconsStrip: "/assets/production/icons/baseball_icons_strip.png",
  attributeIcons: "/assets/production/icons/attribute_icons.png",
  rankBadges: "/assets/production/icons/rank_badges.png",
  resourceCounters: "/assets/production/icons/resource_counters.png",
  decorationsBorders: "/assets/production/icons/decorations_borders.png",
  previewContactSheet: "/assets/production/docs/preview_contact_sheet.png",
} as const;

export const ASSET_PATHS = UI_ASSETS;

export type UiAssetKey = keyof typeof UI_ASSETS;
export type AssetKey = UiAssetKey;
export type CutAssetKey = UiAssetKey;

export const UI_ASSET_LIST: Array<{
  key: UiAssetKey;
  fileName: string;
  title: string;
  description: string;
}> = [
  ["btnMatchLarge", "buttons/btn_match_large.png", "Match Button", "試合へ進む大ボタン"],
  ["btnTrainingLarge", "buttons/btn_training_large.png", "Training Button", "練習へ進む大ボタン"],
  ["btnPlayersLarge", "buttons/btn_players_large.png", "Players Button", "選手一覧の大ボタン"],
  ["btnScheduleLarge", "buttons/btn_schedule_large.png", "Schedule Button", "予定系の大ボタン"],
  ["btnItemSmall", "buttons/btn_item_small.png", "Item Button", "小ボタン"],
  ["btnScoutSmall", "buttons/btn_scout_small.png", "Scout Button", "スカウト小ボタン"],
  ["btnDataSmall", "buttons/btn_data_small.png", "Data Button", "データ小ボタン"],
  ["btnSystemSmall", "buttons/btn_system_small.png", "System Button", "システム小ボタン"],
  ["tabsPrimaryRow", "buttons/tabs_primary_row.png", "Primary Tabs", "主要タブ列"],
  ["btnConfirmCancelPair", "buttons/btn_confirm_cancel_pair.png", "Confirm Cancel Pair", "決定/キャンセルペア"],
  ["btnConfirmLarge", "buttons/btn_confirm_large.png", "Confirm Button", "決定ボタン"],
  ["btnCancelLarge", "buttons/btn_cancel_large.png", "Cancel Button", "キャンセルボタン"],
  ["controlCheckboxes", "buttons/control_checkboxes.png", "Checkboxes", "チェックボックス部品"],
  ["controlTogglesSliders", "buttons/control_toggles_sliders.png", "Toggles Sliders", "トグルとスライダー"],
  ["controlPaginationTabs", "buttons/control_pagination_tabs.png", "Pagination Tabs", "ページ送りとタブ"],
  ["badgesNotifications", "buttons/badges_notifications.png", "Badges Notifications", "通知バッジ"],
  ["mascotStanding", "mascots/mascot_standing.png", "Standing Mascot", "立ちマスコット"],
  ["mascotPointing", "mascots/mascot_pointing.png", "Pointing Mascot", "案内マスコット"],
  ["mascotClipboard", "mascots/mascot_clipboard.png", "Clipboard Mascot", "メモ持ちマスコット"],
  ["mascotCheering", "mascots/mascot_cheering.png", "Cheering Mascot", "応援マスコット"],
  ["mascotSweating", "mascots/mascot_sweating.png", "Sweating Mascot", "注意マスコット"],
  ["mascotFacesStrip", "mascots/mascot_faces_strip.png", "Mascot Faces", "マスコット表情"],
  ["mascotBadge", "mascots/mascot_badge.png", "Mascot Badge", "エンブレム風マスコット"],
  ["panelLargeBlueHeader", "panels/panel_large_blue_header.png", "Large Panel", "青見出し大パネル"],
  ["panelNoticeList", "panels/panel_notice_list.png", "Notice List", "お知らせリスト"],
  ["panelNoteMemo", "panels/panel_note_memo.png", "Note Memo", "メモパネル"],
  ["panelGoalChecklist", "panels/panel_goal_checklist.png", "Goal Checklist", "目標チェックリスト"],
  ["panelStatusGroup", "panels/panel_status_group.png", "Status Group", "ステータス表示"],
  ["dialogModalLarge", "panels/dialog_modal_large.png", "Large Dialog", "大型モーダル"],
  ["dialogModalSmall", "panels/dialog_modal_small.png", "Small Dialog", "小型モーダル"],
  ["dialogueBoxMascotLeft", "panels/dialogue_box_mascot_left.png", "Dialogue Box", "マスコット会話枠"],
  ["tutorialPopup", "panels/tutorial_popup.png", "Tutorial Popup", "チュートリアル枠"],
  ["playerCardGold", "cards/player_card_gold.png", "Gold Player Card", "金色選手カード"],
  ["playerCardsSet", "cards/player_cards_set.png", "Player Cards", "選手カードセット"],
  ["rosterTableRows", "cards/roster_table_rows.png", "Roster Rows", "選手一覧行"],
  ["scoreboardMain", "scoreboards/scoreboard_main.png", "Scoreboard", "試合スコアボード"],
  ["resultStamps", "scoreboards/result_stamps.png", "Result Stamps", "勝利/敗北スタンプ"],
  ["trainingResultPanel", "scoreboards/training_result_panel.png", "Training Result", "練習結果パネル"],
  ["calendarMonth", "schedule/calendar_month.png", "Calendar", "月間カレンダー"],
  ["weeklyScheduleCards", "schedule/weekly_schedule_cards.png", "Weekly Schedule", "週間予定カード"],
  ["locationTiles", "schedule/location_tiles.png", "Location Tiles", "学校施設タイル"],
  ["missionPanel", "schedule/mission_panel.png", "Mission Panel", "ミッションパネル"],
  ["rewardPopup", "schedule/reward_popup.png", "Reward Popup", "報酬ポップアップ"],
  ["saveSlots", "schedule/save_slots.png", "Save Slots", "セーブスロット"],
  ["baseballIconsStrip", "icons/baseball_icons_strip.png", "Baseball Icons", "野球アイコン"],
  ["attributeIcons", "icons/attribute_icons.png", "Attribute Icons", "能力アイコン"],
  ["rankBadges", "icons/rank_badges.png", "Rank Badges", "ランクバッジ"],
  ["resourceCounters", "icons/resource_counters.png", "Resource Counters", "リソース表示"],
  ["decorationsBorders", "icons/decorations_borders.png", "Decorations", "装飾と区切り線"],
  ["previewContactSheet", "docs/preview_contact_sheet.png", "Preview Contact Sheet", "本番アセット一覧"],
].map(([key, fileName, title, description]) => ({
  key: key as UiAssetKey,
  fileName,
  title,
  description,
}));

export const CUT_ASSET_LIST = UI_ASSET_LIST;
