import {awakeningCosts} from './development';
import { formatFieldInnings } from './defense';
import { useEffect,useState,type CSSProperties } from 'react';
import { ArrowRight,Check,Diamond,Flame,Gift,Medal,Shield,Sparkles,Star,Target,Trophy,Zap } from 'lucide-react';
import { canBat,activeUzrCount,rosterInfo,contextFor,deltaInfo,formatAvg,formatIP,playerMap,players,saberFor,sourceInfo,teamById,uzrInfo,uzrCoverage,type Player } from './data';
import { effectiveOverall,scoutWeight,type GameState,type ScoutFocus } from './engine';
import { buildByStrategy,captainPool,claimAllMilestones,claimMilestone,clubLevel,establishClub,milestonesFor,trainPlayer,upgradeStadium } from './franchise';
import { battingMetrics,displayMetric as d,displayPercent as pct,leagueContext,pitchingMetrics } from './sabermetrics';

import { isCareer,currencyName } from './progression';
const colors=['#d7b65f','#ee7866','#73b5ff','#ae86ff','#67d9a1','#f18fbe'];
const marks=['★','D','⚡','W','S','N'];
type ClubProps={state:GameState;setState:(s:GameState)=>void;notify:(s:string)=>void};
export function ClubStrip({state,onClub,onLab}:{state:GameState;onClub:()=>void;onLab:()=>void}){
 const f=state.franchise,ready=milestonesFor(state).filter(m=>!f.claimed.includes(m.id)&&m.value(state)>=m.goal).length;
 return <section className="club-strip"><span className="custom-crest" style={{'--crest':f.color} as CSSProperties}>{f.mark}</span><div><small>{f.established?`${f.city.toUpperCase()} · CLUB LEVEL ${clubLevel(state)}`:'CREATE YOUR OWN FRANCHISE'}</small><strong>{f.established?state.name:'あなただけの球団を、ここから。'}</strong><span>{f.established?`${f.motto}　育成ポイント ${f.points.toLocaleString()}`:'名前・カラー・初代URスターを選んで、新球団を設立。'}</span></div><button className="btn gold" onClick={onClub}>{f.established?(ready?`報酬 ${ready}件を受け取る`:'球団を育てる'):'球団をつくる'}<ArrowRight size={15}/></button><button className="btn outline" onClick={onLab}>戦力を分析</button></section>;
}
export function SaberDetail({player}:{player:Player}){
 const s=saberFor(player),b=s.batting,p=s.pitching;
 const metrics=player.role==='batter'?[['出塁率',d(b?.obp)],['ISO',d(b?.iso)],['BABIP',d(b?.babip)],['BB%',pct(b?.bbPct)],['K%',pct(b?.kPct)],['OPS',d(b?.ops)]]:[['FIP',d(p?.fip,2)],['WHIP',d(p?.whip)],['K−BB%',pct(p?.kMinusBb)],['K%',pct(p?.kPct)],['BB%',pct(p?.bbPct)],['HR/9',d(p?.hr9,2)]];
 return <div className="saber-detail"><div className="eyebrow">{player.dataYear} · SABERMETRICS</div><div className="saber-cells">{metrics.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><p className="fine-print">{player.role==='pitcher'?'FIPは同年リーグの投球回で加重した平均防御率に校正。球場補正なし。':'公開打撃成績から算出。打席数も合わせて確認できます。'}</p>{player.war!==null&&<a className="saber-source" href={deltaInfo.source} target="_blank" rel="noreferrer">DELTA公開値 · {player.war!==null?`WAR ${d(player.war,1)} · `:''}{deltaInfo.fetchedAt.slice(0,10)}取得 / 集計基準日は掲載なし</a>}</div>;
}
export function ClubPage({state,setState,notify}:ClubProps){
 const f=state.franchise,milestones=milestonesFor(state);
 const [name,setName]=useState(state.name),[city,setCity]=useState(f.city),[motto,setMotto]=useState(f.motto),[color,setColor]=useState(f.color),[mark,setMark]=useState(f.mark);
 const [captain,setCaptain]=useState(f.captain??captainPool()[0].id),[trainee,setTrainee]=useState(state.lineup[0]);
 const [celebrate,setCelebrate]=useState(false);
 const selected=playerMap[trainee],level=state.training[trainee]??0,needed=awakeningCosts[level]??0;
 const claim=(id:string)=>{const next=claimMilestone(state,id);if(next===state)return;setState(next);setCelebrate(true);const m=milestones.find(m=>m.id===id)!;notify(`${m.title} 達成！ ${m.gems.toLocaleString()}${currencyName(state)} ＋ ${m.points}育成ポイント`);};
 return <><div className={`franchise-banner ${celebrate?'celebrate':''}`} onAnimationEnd={()=>setCelebrate(false)} style={{'--crest':color} as CSSProperties}><div className="franchise-title"><div className="eyebrow light">BUILD YOUR DYNASTY</div><h2>{f.established?'推しを集めて、常勝軍団へ。':'その名前が、伝説になる。'}</h2><p>球団をつくる。選手を育てる。143試合で証明する。</p><div className="club-level"><Medal size={20}/><strong>CLUB Lv.{clubLevel(state)}</strong><span>{f.xp%700} / 700 XP</span></div><div className="club-xp"><i style={{width:`${f.xp%700/7}%`}}/></div></div><div className="franchise-uniform"><svg viewBox="0 0 230 240" role="img" aria-label="オリジナル球団のユニフォーム"><path d="m68 25 33-14q14 21 28 0l33 14 53 37-27 39-26-16 6 138q-53 13-106 0l6-138-26 16-27-39Z" fill="#f4f2e7"/><path d="m68 25 33-14 14 22 14-22 33 14-32 35h-30Z" fill={color}/><path d="M115 60v170M61 126h108M61 136h108" stroke={color} strokeWidth="4"/><text x="115" y="112" textAnchor="middle" fill="#153a32" fontSize="36" fontWeight="900">{mark}</text><text x="115" y="198" textAnchor="middle" fill="#153a32" fontSize="44" fontWeight="900">09</text></svg><strong>{name||'YOUR CLUB'}</strong><span>{city} BASEBALL CLUB</span></div></div>
 <div className="franchise-grid"><section className="panel"><div className="eyebrow">CLUB IDENTITY</div><h2>球団のアイデンティティ</h2><div className="club-fields"><label>球団名<input aria-label="オリジナル球団名" maxLength={20} value={name} onChange={e=>setName(e.target.value)}/></label><label>ホームタウン<input aria-label="ホームタウン" maxLength={12} value={city} onChange={e=>setCity(e.target.value)}/></label><label className="full">スローガン<input aria-label="スローガン" maxLength={40} value={motto} onChange={e=>setMotto(e.target.value)}/></label></div><div className="identity-choices"><span>エンブレム</span><div>{marks.map(m=><button key={m} className={mark===m?'selected':''} onClick={()=>setMark(m)} aria-label={`エンブレム ${m}`} aria-pressed={mark===m}>{m}</button>)}</div></div><div className="identity-choices"><span>チームカラー</span><div>{colors.map((c,i)=><button key={c} className={`color-swatch ${color===c?'selected':''}`} style={{background:c}} onClick={()=>setColor(c)} aria-label={`カラー ${['ゴールド','レッド','ブルー','パープル','グリーン','ピンク'][i]}`} aria-pressed={color===c}>{color===c&&<Check size={16}/>}</button>)}</div></div>
 {!f.established&&<div className="captain-draft"><span><Star size={17}/>初代スターを指名 · UR 1人を獲得</span><select aria-label="初代スターを指名" value={captain} onChange={e=>setCaptain(e.target.value)}>{captainPool().map(p=><option key={p.id} value={p.id}>{p.name} · {teamById(p.team).short} · {p.position} · OVR {p.overall}</option>)}</select><p>{playerMap[captain].traits.join(' / ')}<br/>設立ボーナス：選んだUR ＋ 2,700ジェム</p></div>}
 <button className="btn primary full-button" disabled={!name.trim()||!city.trim()} onClick={()=>{const next=establishClub(state,{city:city.trim(),mark,color,motto},name,captain);if(next===state)return;setState(next);setCelebrate(true);notify(f.established?'球団デザインを更新しました。':`${name}、始動！ UR ${playerMap[captain].name}と2,700ジェムを獲得。チーム編成から起用できます。`);}}><Sparkles size={17}/>{f.established?'球団デザインを保存':'球団設立 ＋ UR選手を獲得'}</button><p className="fine-print">セ・リーグの兵庫枠で参戦するファンタジー球団です。デザインはいつでも変更できます。</p></section>
 <section className="panel training-panel"><div className="eyebrow">PLAYER DEVELOPMENT</div><h2>推しの限界を、引き上げろ。</h2><div className="training-bank"><Zap size={21}/><strong>{f.points.toLocaleString()}</strong><span>育成ポイント</span></div><select aria-label="育成する選手" value={trainee} onChange={e=>setTrainee(e.target.value)}>{Object.keys(state.owned).map(id=>playerMap[id]).sort((a,b)=>b.overall-a.overall).map(p=><option key={p.id} value={p.id}>{p.name} · Lv.{state.training[p.id]??0} · {p.rarity}</option>)}</select><div className="training-preview"><span className={`rarity-label ${selected.rarity}`}>{selected.rarity}</span><h3>{selected.name}</h3><div className="training-overall"><span>OVR</span><strong>{effectiveOverall(selected,state.owned,state.training)}</strong>{level<5&&<><ArrowRight/><b>{Math.min(99,effectiveOverall(selected,state.owned,state.training)+1)}</b></>}</div><div className="training-stars">{[1,2,3,4,5].map(i=><Star key={i} size={26} fill={i<=level?'currentColor':'none'} className={i<=level?'active':''}/>)}</div></div><button className="btn gold full-button" disabled={level>=5||f.points<needed} onClick={()=>{setState(trainPlayer(state,trainee));setCelebrate(true);notify(`${selected.name}のトレーニングがLv.${level+1}に！ 試合能力 ＋1`);}}><Zap size={17}/>{level>=5?'TRAINING MAX':`トレーニング ＋1 / ${needed}pt`}</button><p className="fine-print">毎試合15pt。育成は最大＋5、重複覚醒と合わせて最大＋10。現実の成績は変更せず、ゲームの試合能力に補正します。</p><div className="stadium-upgrade"><div><strong>ホームスタジアム Lv.{f.stadium}</strong><small>毎試合の{currencyName(state)} ＋{(f.stadium-1)*5}</small></div><button className="btn outline" disabled={f.stadium>=5||f.points<f.stadium*700} onClick={()=>{setState(upgradeStadium(state));notify(`球場がLv.${f.stadium+1}に進化！ 毎試合の報酬が増えました。`);}}>{f.stadium>=5?'MAX':`増築 ${f.stadium*700}pt`}</button></div></section></div>
 <section className="panel"><div className="section-title"><div><div className="eyebrow">MILESTONE REWARDS</div><h2>{isCareer(state)?'次の達成が、次の一枚になる。':'次の達成が、次の10連になる。'}</h2></div><button className="btn gold" disabled={!milestones.some(m=>!f.claimed.includes(m.id)&&m.value(state)>=m.goal)} onClick={()=>setState(claimAllMilestones(state))}><Gift size={17}/>達成報酬をまとめて受け取る</button></div><div className="mission-grid">{milestones.map(m=>{const value=Math.min(m.goal,m.value(state)),claimed=f.claimed.includes(m.id),ready=value>=m.goal;return <div key={m.id} className={`mission ${ready&&!claimed?'ready':''}`}><div><small>{claimed?'COMPLETE':ready?'REWARD UNLOCKED':'CHALLENGE'}</small><h3>{m.title}</h3><p>{m.detail}</p></div><div className="mission-meter"><i style={{width:`${value/m.goal*100}%`}}/></div><div className="mission-count"><span>{value} / {m.goal}</span><span>＋{m.points}pt</span></div><div className="mission-reward"><span><Diamond size={16}/>{m.gems.toLocaleString()}</span><button disabled={!ready||claimed} onClick={()=>claim(m.id)}>{claimed?<><Check size={14}/>受取済</>:ready?'受け取る':'挑戦中'}</button></div></div>;})}</div></section></>;
}

export function StrategyBar({state,setState,notify}:ClubProps){return <section className="strategy-bar"><span><Target size={18}/><strong>編成のこだわり</strong></span>{([['balanced','総合力'],['onbase','出塁重視'],['power','長打重視'],['defense','守備重視']] as const).map(([key,label])=><button className="btn outline" key={key} onClick={()=>{setState(buildByStrategy(state,key));notify(`${label}で選手を選び、上位に出塁率の高い打者を編成しました。`);}}>{label}</button>)}</section>;}

export function ScoutFocusPicker({focus,setFocus}:{focus:ScoutFocus;setFocus:(f:ScoutFocus)=>void}){
 const options=[{id:'all',icon:Sparkles,title:'オールスター',sub:'すべての選手を均等に'},{id:'power',icon:Flame,title:'ホームラン祭',sub:'パワーB（70）以上 ×3'},{id:'pitching',icon:Target,title:'エース降臨',sub:'投手の抽選重み ×3'},{id:'defense',icon:Shield,title:'鉄壁の守備',sub:'守備B（70）以上の野手 ×3'}] as const;
 return <section className="focus-section"><div className="section-title"><div><div className="eyebrow">CHOOSE YOUR SCOUT</div><h2>欲しいのは、一発か。鉄壁か。</h2></div><span className="small-muted">レアリティの確率は共通</span></div><div className="focus-grid">{options.map(o=><button key={o.id} className={focus===o.id?'selected':''} onClick={()=>setFocus(o.id)} aria-pressed={focus===o.id}><o.icon size={25}/><strong>{o.title}</strong><small>{o.sub}</small>{focus===o.id&&<Check size={17}/>}</button>)}</div>{focus!=='all'&&<details className="focus-odds"><summary>選手ごとの提供割合を確認（通常1枠）</summary><p>同じレアリティ内の対象選手の重みが3倍になります。個別確率＝レアリティ確率×重み÷そのレアリティの重み合計。UR確定枠ではUR内の条件付き確率です。</p><div className="odds-list">{players.filter(p=>scoutWeight(p,focus)===3).map(p=>{const total=players.filter(x=>x.rarity===p.rarity).reduce((n,x)=>n+scoutWeight(x,focus),0),rate={UR:.03,SSR:.12,SR:.35,R:.5}[p.rarity]*3/total;return <span key={p.id}>{p.rarity} {p.name}<b>{(rate*100).toFixed(3)}%</b></span>;})}</div></details>}</section>;
}

export function SaberLab({state,onPlayer}:{state:GameState;onPlayer:(p:Player)=>void}){
 const [dataset,setDataset]=useState<'real'|'game'>('real'),[mode,setMode]=useState<'bat'|'pit'|'field'>('bat'),[scope,setScope]=useState('all'),[sort,setSort]=useState('ops'),[sample,setSample]=useState(true),[search,setSearch]=useState(''),[limit,setLimit]=useState(80);
 useEffect(()=>setLimit(80),[dataset,mode,scope,sort,sample,search]);
 const lineup=state.lineup.map(id=>playerMap[id]),fielders=lineup.filter(p=>state.defense[p.id]!=='DH'),pitchers=state.pitchers.map(id=>playerMap[id]),outs=pitchers.reduce((n,p)=>n+(p.pitching?.outs??0),0);
 const avgObp=lineup.reduce((n,p)=>n+(saberFor(p).batting?.obp??0),0)/9,teamFip=outs?pitchers.reduce((n,p)=>n+(saberFor(p).pitching?.fip??0)*(p.pitching?.outs??0),0)/outs:null;
 const simContext=leagueContext(Object.values(state.season.pitching).map(p=>({pitching:p})));
 type Row={player:Player;team:string;sample:number|null;values:Record<string,number|null>};
 const realRows:Row[]=players.filter(p=>mode==='field'||(mode==='pit'?p.role==='pitcher':canBat(p))).map(player=>{const saber=saberFor(player);return {player,team:player.team,sample:mode==='field'?null:mode==='pit'?player.pitching?.outs??null:player.batting?.pa??null,values:{...(mode==='pit'?saber.pitching:saber.batting),hr:player.batting?.hr??null,war:player.war,...(mode==='field'?{contact:player.ratings.contact,power:player.ratings.power,speed:player.ratings.speed,arm:player.ratings.arm,field:player.ratings.field,catching:player.ratings.catching}:{})}};});
 const simRows:Row[]=mode==='pit'?Object.values(state.season.pitching).map(p=>({player:playerMap[p.playerId],team:p.team,sample:p.outs,values:{...pitchingMetrics(p,simContext.fipConstant)}})):Object.values(state.season.batting).map(b=>({player:playerMap[b.playerId],team:b.team,sample:b.pa,values:{...battingMetrics(b),hr:b.hr}}));
 const rows=(dataset==='game'&&state.season.model!=='2026-dips'?[]:dataset==='real'?realRows:simRows).filter(r=>(scope==='all'||(dataset==='real'?state.owned[r.player.id]:r.team===state.club))&&r.player.name.replace(/\s/g,'').includes(search.replace(/\s/g,''))&&(mode==='field'||!sample||(r.sample??0)>=(mode==='pit'?60:100))).sort((a,b)=>{const x=a.values[sort],y=b.values[sort];if(x==null)return y==null?0:1;if(y==null)return -1;return ['fip','whip','era'].includes(sort)?x-y:y-x;});
 const columns=mode==='bat'?[['ops','OPS'],['obp','出塁率'],['iso','ISO'],['babip','BABIP'],['bbPct','BB%'],['kPct','K%'],['hr','本塁打']]:mode==='pit'?[['fip','FIP'],['era','防御率'],['whip','WHIP'],['kMinusBb','K−BB%'],['kPct','K%'],['bbPct','BB%']]:[['contact','ミート'],['power','パワー'],['speed','走力'],['arm','肩'],['field','守備'],['catching','捕球']];
 if(dataset==='real'&&mode!=='field')columns.push(['war','WAR*']);
 return <><div className="lab-intro"><div><div className="eyebrow">THE EDGE IS IN THE NUMBERS</div><h2>打率の、その先を読む。</h2><p>出塁でつなぐ。長打で還す。三振と守備で守り抜く。</p></div><span className="data-cutoff"><i/>{sourceInfo.asOf}現在<br/><small>公式名簿 · {players.length}人</small></span></div>
 <div className="lab-summary"><div><small>打線の平均出塁率</small><strong>{d(avgObp)}</strong><span>現在のオーダー / 現実の実績</span></div><div><small>投手陣の投球回加重FIP</small><strong>{d(teamFip,2)}</strong><span>現在の投手陣 / 現実の実績</span></div><div><small>スタメンの平均守備力</small><strong>{Math.round(fielders.reduce((n,p)=>n+p.ratings.field,0)/Math.max(1,fielders.length))}</strong><span>DHを除く基礎能力の平均</span></div></div>
 <section className="panel"><div className="lab-controls"><div className="segments"><button className={dataset==='real'?'active':''} onClick={()=>setDataset('real')}>現実の2026年</button><button className={dataset==='game'?'active':''} onClick={()=>{setDataset('game');if(mode==='field'){setMode('bat');setSort('ops');}}}>ゲーム内シーズン</button></div><select aria-label="分析対象" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">全選手</option><option value="mine">{dataset==='real'?'獲得済みの選手':'マイチーム'}</option></select></div>
 <div className="lab-filters"><div className="segments">{([['bat','打撃','ops'],['pit','投球','fip'],['field','選手能力','field']] as const).map(([key,label,order])=><button key={key} className={mode===key?'active':''} disabled={key==='field'&&dataset==='game'} onClick={()=>{setMode(key);setSort(order);}}>{label}</button>)}</div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="選手名で検索" aria-label="分析する選手名"/>{mode!=='field'&&<label className="owned-toggle"><input type="checkbox" checked={sample} onChange={e=>setSample(e.target.checked)}/>{mode==='pit'?'20投球回以上':'100打席以上'}</label>}</div>
 {dataset==='game'&&state.season.model!=='2026-dips'&&<p className="notice">旧モデルのシーズンは「成績・記録」で確認できます。次シーズンから詳細指標を集計します。</p>}<p className="fine-print">{mode==='field'?'全選手のゲーム用基礎能力。覚醒・育成・調子の補正前です。':'列名で並び替え。少ない打席・投球回では指標が大きく変動します。'}{dataset==='real'&&mode!=='field'&&' WAR*はDELTA公開リーダーの収録値のみ。集計基準日は掲載されていません。'}</p>
 <div className="table-scroll"><table className="data-table saber-table"><thead><tr><th>#</th><th>選手</th><th>{mode==='field'?'位置':mode==='pit'?'投球回':'打席'}</th>{columns.map(([key,label])=><th key={key} aria-sort={sort===key?(['fip','era','whip'].includes(key)?'ascending':'descending'):'none'}><button onClick={()=>setSort(key)}>{label}{sort===key?' ▾':''}</button></th>)}</tr></thead><tbody>{rows.slice(0,limit).map((row,i)=><tr key={`${row.team}-${row.player.id}`}><td>{i+1}</td><td><button data-player-id={row.player.id} onClick={()=>onPlayer(row.player)}><b>{row.player.name}</b><small>{dataset==='game'&&row.team===state.club?state.name:teamById(row.team).short}{row.player.provisional?' · 暫定':''}</small></button></td><td>{mode==='field'?row.player.positions.join('/'):row.sample===null?'—':mode==='pit'?formatIP(row.sample):row.sample}</td>{columns.map(([key])=><td key={key} className={sort===key?'stat-highlight':''}>{key.endsWith('Pct')||key==='kMinusBb'?pct(row.values[key]):d(row.values[key],mode==='field'||key==='hr'?0:key==='war'?1:['fip','era'].includes(key)?2:3)}</td>)}</tr>)}</tbody></table></div>
 {!rows.length&&<div className="empty-state"><h3>条件に合う成績がありません。</h3><p>試合を進めるか、打席・投球回の条件を外してください。</p></div>}<p className="fine-print">{rows.length}件中、{Math.min(limit,rows.length)}件を表示</p>{limit<rows.length&&<button className="btn outline" onClick={()=>setLimit(n=>n+80)}>さらに80人を見る</button>}</section>
 <section className="panel metric-guide"><div className="eyebrow">SABERMETRICS FIELD GUIDE</div><h2>数字から、次のオーダーを。</h2><div>{[['出塁率 / BB%','出塁率は安打・四球・死球による出塁の割合。BB%は打席に占める四球の割合。上位打線を選ぶ手がかりです。'],['ISO / BABIP','ISOは長打率−打率で長打力の目安。BABIPは本塁打以外の打球が安打になる割合です。打席数も確認しましょう。'],['FIP / K−BB%','FIPは本塁打・四死球・奪三振から推定する失点抑止力。K−BB%は奪三振率と与四球率の差です。'],['適性と育成','守備適性を合わせ、打順を整えることがチーム力につながります。覚醒と育成の補正はカードに反映されます。']].map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div><div className="source-links"><a href="https://npb.jp/bis/2026/stats/" target="_blank" rel="noreferrer">NPB公式2026年成績 ↗</a><a href={deltaInfo.source} target="_blank" rel="noreferrer">DELTA公開WAR ↗</a><a href="https://library.fangraphs.com/pitching/fip/" target="_blank" rel="noreferrer">FIPの算式 ↗</a></div></section></>;
}

