import {useState} from 'react';
import {ArrowRight,Check,Gift,Search,Shield,Target,Ticket,TrendingUp,Users,Zap} from 'lucide-react';
import {fitsPosition,formatAvg,matchesPlayerName,playerMap,teamById,type Player} from './data';
import {effectiveOverall,nextMatchPreview,rankings,type GameState} from './engine';
import {benchUpgrades} from './career-roster';
import {contractPool,nextContract,seasonBatting,seasonGoals} from './ambitions';
import {CardAbilities} from './CardAbilities';
import './manager.css';

export function ManagerDesk({state,onTeam,onScout,onClub,onSeason,onClaim,onEquip}:{state:GameState;onTeam:()=>void;onScout:()=>void;onClub:()=>void;onSeason:()=>void;onClaim?:()=>void;onEquip?:(id:string)=>void}){
 const next=nextMatchPreview(state),bat=seasonBatting(state),rank=rankings(state.season,teamById(state.club).league).findIndex(t=>t.team===state.club)+1;
 const upgrades=benchUpgrades(state),weak=[...state.lineup].sort((a,b)=>effectiveOverall(playerMap[a],state.owned,state.training)-effectiveOverall(playerMap[b],state.owned,state.training))[0];
 const goals=seasonGoals(state),ready=goals.filter(g=>!g.claimed&&g.value>=g.goal),pending=goals.filter(g=>!g.claimed),contract=nextContract(state);
 return <div className="manager-desk">
  <section className="panel next-match"><div><div className="eyebrow">{next?'NEXT MATCHUP':'SEASON RESULT'}</div><h2>{next?`次は、${teamById(next.opponent).short}戦。`:`今季はリーグ${rank}位。`}</h2><p>{next?`第${state.season.day+1}戦 · ${next.home===state.club?'ホーム':'ビジター'} · ${state.season.day>=45&&state.season.day<63?'セ・パ交流戦':'リーグ公式戦'}`:'143試合の記録を振り返り、次の戦いへ。'}</p></div>{next?<div className="next-starters">{[[next.mine,'自チームの先発'],[next.theirs,'相手の先発']].map(([id,label])=><div key={label}><small>{label}</small><strong data-player-id={id}>{playerMap[id].name}</strong><span>{playerMap[id].throws}投 · {playerMap[id].ratings.velocity}km/h · 制球{playerMap[id].ratings.control}</span></div>)}</div>:<button className="btn primary" onClick={onSeason}>年間レポートへ <ArrowRight size={16}/></button>}</section>
  <section className="panel manager-season"><div className="section-title"><div><div className="eyebrow">OUR NUMBERS</div><h2>強くなった分を、成績で。</h2></div><button className="text-button" onClick={onSeason}>{state.season.day?`${rank}位 · ${state.season.day}試合`:'開幕前'} <ArrowRight size={15}/></button></div><div className="manager-stats">{[['チーム打率',bat.ab?formatAvg(bat.avg):'—'],['本塁打',bat.hr],['打点',bat.rbi],['OPS',bat.ab?formatAvg(bat.ops):'—']].map(([key,v])=><div key={key}><small>{key}</small><b>{v}</b></div>)}</div></section>
  <section className="panel manager-advice"><div className="section-title"><div><div className="eyebrow">MANAGER'S NEXT MOVE</div><h2>次の一手を、決めよう。</h2></div><Target size={23}/></div><div className="advice-grid"><article><Users size={21}/><small>オーダー診断</small>{upgrades[0]?<><h3>{playerMap[upgrades[0].id].name}を起用候補に。</h3><p>{upgrades[0].upgrade.position}の{playerMap[upgrades[0].upgrade.oldId].name}と比較。適性を含む起用評価が＋{upgrades[0].upgrade.gain.toFixed(1)}。</p><button className="text-button" onClick={()=>onEquip?.(upgrades[0].id)}>この選手を起用 <ArrowRight size={15}/></button></>:<><h3>{state.defense[weak]}の選手層を厚く。</h3><p>{playerMap[weak].name}の総合力は{effectiveOverall(playerMap[weak],state.owned,state.training)}。能力から見る補強候補です。</p><button className="text-button" onClick={onScout}>補強を考える <ArrowRight size={15}/></button></>}</article><article><Zap size={21}/><small>育成も、勝利への近道</small><h3>育成ポイント {state.franchise.points.toLocaleString()}pt</h3><p>Lv.1は100ptで能力＋1。獲得した選手も、最初からいる選手も強化できます。</p><button className="text-button" onClick={onClub}>育てる選手を選ぶ <ArrowRight size={15}/></button></article><article><Shield size={21}/><small>守備と打順</small><h3>{state.lineup.some(id=>!fitsPosition(playerMap[id],state.defense[id]))?'適性外の守備を見直そう。':'一人の起用で、試合が変わる。'}</h3><p>ミート・パワーだけでなく、守備位置と先発・救援の役割も大切です。</p><button className="text-button" onClick={onTeam}>能力を比べて編成 <ArrowRight size={15}/></button></article></div></section>
  <section className="panel season-goals"><div className="section-title"><div><div className="eyebrow">SEASON {String(state.season.number).padStart(2,'0')} · CLUB CHALLENGES</div><h2>このチームで、ひとつずつ。</h2></div><span>{goals.filter(g=>g.claimed||g.value>=g.goal).length} / {goals.length}達成</span></div><div className="goal-grid">{(pending.length?pending:goals).slice(0,3).map(g=><div key={g.id} className={g.claimed||g.value>=g.goal?'complete':''}><small>{g.claimed?'✓ 受取済み':g.value>=g.goal?'✓ 達成！':g.detail}</small><strong>{g.title}</strong><div className="goal-progress" role="progressbar" aria-label={g.title} aria-valuemin={0} aria-valuemax={g.goal} aria-valuenow={Math.min(g.goal,g.value)}><i style={{width:`${Math.min(100,g.value/g.goal*100)}%`}}/></div><span>{Math.min(g.value,g.goal)} / {g.goal}<b>＋{g.reward}pt</b></span><small>＋育成{g.training}pt</small></div>)}</div><div className="goals-footer"><small>毎シーズン更新。達成報酬の取り忘れは翌年へ進む際に自動受取。</small>{ready.length>0&&<button className="btn gold" onClick={onClaim}><Gift size={16}/>{ready.length}件の報酬を受け取る</button>}</div></section>
  {contract&&<button className="contract-alert" onClick={onScout}><Ticket size={26}/><span><strong>{contract.rarity}指名契約が届いています。</strong><small>好きな選手を1人選んで、チームに迎えよう。追加ポイント不要。</small></span><ArrowRight size={20}/></button>}
 </div>;
}

export function ContractBoard({state,onSign}:{state:GameState;onSign?:(id:string)=>void}){
 const [search,setSearch]=useState(''),[position,setPosition]=useState('all'),[selected,setSelected]=useState(''),[limit,setLimit]=useState(12);
 const contract=nextContract(state),nextNumber=Math.floor(state.pulls/10)+1,until=10-state.pulls%10;
 const pool=contractPool(state).filter(p=>matchesPlayerName(p,search)&&(position==='all'||position==='投'?position==='all'||p.role==='pitcher':p.role==='batter'&&fitsPosition(p,position))).sort((a,b)=>b.overall-a.overall);
 const chosen=pool.find(p=>p.id===selected);
 return <section className="panel contract-board"><div className="section-title"><div><div className="eyebrow">YOUR CHOICE · SELECT CONTRACT</div><h2><Ticket size={24}/>{contract?`${contract.rarity}選手を、あなたの指名で。`:'運だけに、任せない。'}</h2></div><span className="contract-badge">{contract?'受取可能':`あと${until}枚`}</span></div><p>通常スカウト10枚ごとに、好きな選手を1人指名。SR → SSRを交互に獲得できます。通常の確定枠とは別の特典です。</p>
 {!contract?<div className="contract-progress"><div role="progressbar" aria-label="次の指名契約まで" aria-valuemin={0} aria-valuemax={10} aria-valuenow={state.pulls%10}><i style={{width:`${state.pulls%10*10}%`}}/></div><span>{state.pulls%10}/10枚 · 次は{nextNumber%2?'SR':'SSR'}指名契約</span></div>:<><div className="contract-filters"><label className="search-box"><Search size={16}/><input placeholder="指名したい選手を検索" aria-label="指名選手を検索" value={search} onChange={e=>{setSearch(e.target.value);setLimit(12);}}/></label><select aria-label="指名選手のポジション" value={position} onChange={e=>{setPosition(e.target.value);setLimit(12);}}>{[['all','全ポジション'],['投','投手'],['捕','捕手'],['一','一塁'],['二','二塁'],['三','三塁'],['遊','遊撃'],['外','外野']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></div><div className="contract-players">{pool.slice(0,limit).map(p=><ContractPlayer key={p.id} player={p} owned={!!state.owned[p.id]} selected={selected===p.id} onSelect={()=>setSelected(p.id)}/>)}</div>{!pool.length&&<p>条件に合う選手はいません。検索やポジションを変更してください。</p>}{pool.length>limit&&<button className="btn outline load-more" onClick={()=>setLimit(n=>n+12)}>さらに12人を見る</button>}{chosen&&<div className="contract-confirm"><span><small>選択中 · 第{contract.number}回指名契約</small><strong>{chosen.name}</strong></span><button className="btn gold" onClick={()=>{onSign?.(chosen.id);setSelected('');}}><Check size={17}/>この選手と契約 · 追加pt不要</button></div>}<small className="fine-print">ポイント・UR確定カウント・通常スカウト枚数は消費しません。指名契約は各回1回限りです。</small></>}
 </section>;
}
function ContractPlayer({player:p,owned,selected,onSelect}:{player:Player;owned:boolean;selected:boolean;onSelect:()=>void}){return <button className={`contract-player ${selected?'selected':''}`} aria-pressed={selected} onClick={onSelect}><span><small>{p.rarity} · {teamById(p.team).short} · {p.positions.join('/')}</small><strong>{p.name}</strong><em>{owned?'所持済み · 覚醒対象':'未獲得'}</em></span><b>{p.overall}<small>OVR</small></b><CardAbilities player={p}/>{selected&&<Check size={16}/>}</button>;}

export function BenchAdvice({state,onEquip}:{state:GameState;onEquip:(id:string)=>void}){const list=benchUpgrades(state).slice(0,3);return list.length?<section className="panel bench-advice"><div className="eyebrow">BENCH TO STARTER</div><h2><TrendingUp size={21}/>控えに、起用候補がいます。</h2><div>{list.map(({id,upgrade:u})=><article key={id}><span><strong>{playerMap[id].name}</strong><small>{u.position} · {playerMap[u.oldId].name}と比較</small></span><b>＋{u.gain.toFixed(1)}<small>起用評価</small></b><button className="btn outline" onClick={()=>onEquip(id)}>起用する</button></article>)}</div><p className="fine-print">覚醒・育成・守備適性を含めて比較。入れ替わる選手は控えに残ります。</p></section>:null;}

