import { currencyName,seasonReward,postseasonReward } from './progression';
import { ArrowRight,Check,ChevronsRight,Diamond,Flame,Play,Snowflake,Star,Trophy } from 'lucide-react';
import { useState } from 'react';
import { formatAvg,formatIP,playerMap,teamById,type Player } from './data';
import { battingAverage,era,nextSeason,rankings,type GameResult,type GameState } from './engine';
import { seasonConditions } from './conditions';
import { simulatePostseason,stageLabel,type PostSeries } from './postseason';
import { SeasonBattingReport } from './SeasonBattingReport';

export function SeasonJourney({state,setState,onTeam,onStats,onGame,onPlayer}:{state:GameState;setState:(s:GameState)=>void;onTeam:()=>void;onStats:()=>void;onGame:(g:GameResult)=>void;onPlayer:(p:Player)=>void}) {
 const season=state.season,post=season.postseason,complete=post?.stage==='complete',myRank=rankings(season,teamById(state.club).league).findIndex(t=>t.team===state.club)+1;
 const name=(id:string)=>id===state.club?state.name:teamById(id).short;
 const [working,setWorking]=useState(false);
 const advance=(all:boolean)=>{if(working)return;setWorking(true);setTimeout(()=>{try{setState(simulatePostseason(state,all?60:1));}finally{setWorking(false);}},80);};
 const stage=complete?4:!season.completed?season.day?1:0:post?.stage==='japan'?3:2;
 const milestones=[{day:30,label:'開幕ダッシュ',reward:'育成 450pt'},{day:63,label:'交流戦を突破',reward:'交流戦 18試合'},{day:100,label:'勝負の終盤',reward:'育成 累計1,500pt'},{day:143,label:'143試合、完走',reward:`${seasonReward(state).toLocaleString()}${currencyName(state)} ＋ UR券`}];
 return <section className="season-journey">
  <div className="journey-heading"><div><div className="eyebrow">ROAD TO THE CHAMPIONSHIP · SEASON {String(season.number).padStart(2,'0')}</div><h2>{complete?(post.champion===state.club?'頂点に、あなたの名前を。':'この一年が、次の強さになる。'):season.completed?(myRank<=3?'頂点まで、あと少し。':'来季につながる、最後の戦い。'):'集めたスターで、日本一へ。'}</h2></div><Trophy size={42}/></div>
  <ol className="journey-steps">{['編成','143試合','クライマックス','日本シリーズ','年間レポート'].map((label,i)=><li key={label} className={stage===i?'current':stage>i?'done':''}><span>{stage>i?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><strong>{label}</strong></li>)}</ol>
  {season.completed&&<SeasonBattingReport state={state} onPlayer={onPlayer}/>}
  {!season.completed&&<><div className="journey-milestones">{milestones.map(m=><div key={m.day} className={season.day>=m.day?'done':''}><small>{season.day>=m.day?'✓ 到達':`GAME ${m.day}`}</small><strong>{m.label}</strong><span>{m.reward}</span></div>)}</div><div className="condition-section"><div><Flame size={18}/><strong>今のキープレイヤー</strong><small>第{seasonConditions(state)[0].from}〜{seasonConditions(state)[0].through}戦 · 試合中の補正</small></div><div className="condition-cards">{seasonConditions(state).map(c=>{const player=playerMap[c.playerId];return <button className={c.boost<0?'cold':'hot'} key={c.playerId} data-player-id={c.playerId} onClick={()=>onPlayer(player)}>{c.boost<0?<Snowflake size={17}/>:<Flame size={17}/>}<span><strong>{player.name}</strong><small>{c.boost===5?'絶好調':c.boost>0?'好調':'調整中'} · {c.boost>0?'+':''}{c.boost}</small></span></button>;})}</div></div><button className="text-button" onClick={onTeam}>打順・守備位置・投手の役割を整える <ArrowRight size={16}/></button></>}
  {season.completed&&!complete&&<div className="post-callout"><div><span>{post?stageLabel(post.stage):'POSTSEASON OPEN'}</span><h3>{myRank<=3?`${myRank}位でレギュラーシーズン終了`:'レギュラーシーズン終了'}</h3><p>{myRank<=3?'CSから日本シリーズまで、1試合ずつ采配しよう。':'今季はCS出場圏外。日本一の決定を見届け、来季の編成へ。'}</p><small>年間決着で{postseasonReward(state,false,false).toLocaleString()}{currencyName(state)}。日本シリーズ進出なら{postseasonReward(state,false,true).toLocaleString()}{currencyName(state)}＋UR券1枚、日本一なら{postseasonReward(state,true,true).toLocaleString()}{currencyName(state)}＋UR券2枚。</small></div><div><button className="btn gold" disabled={working} onClick={()=>advance(false)}><Play size={16}/>{working?'試合進行中…':post?'短期決戦を1日進める':'短期決戦を始める'}</button><button className="btn outline" disabled={working} onClick={()=>advance(true)}><ChevronsRight size={16}/>日本一決定まで進める</button></div></div>}
  {post&&<div className="post-bracket">{post.series.map(series=><SeriesTile key={series.id} series={series} club={state.club} name={name} onGame={onGame}/>)}</div>}
  {season.completed&&<SeasonReport state={state} onPlayer={onPlayer}/>}
  {complete&&<div className={`champion-banner ${post.champion===state.club?'my-championship':''}`}><div><Star size={30}/><span>JAPAN SERIES CHAMPION</span><h3>{name(post.champion!)}</h3><p>{post.champion===state.club?`日本一ボーナス：${postseasonReward(state,true,true).toLocaleString()}${currencyName(state)} ＋ UR券2枚 ＋ 育成1,000pt`:'年間決着の報酬を獲得。スターを迎えて、次のシーズンへ。'}</p></div><button className="btn gold" onClick={()=>setState(nextSeason(state))}>次のシーズンへ <ArrowRight size={18}/></button></div>}
  {season.completed&&<div className="journey-footer"><button className="text-button" onClick={onStats}>レギュラーシーズンの全成績 <ArrowRight size={15}/></button><small>短期決戦の成績は143試合の記録と別に保存します。</small></div>}
  <details className="season-rules"><summary>シーズンのルール</summary><p>公式戦143試合（リーグ内125・交流戦18）。両リーグDH制、延長12回。上位3球団がCSへ進みます。CSファーストは最大3試合、ファイナルは最大6試合・優勝チームに1勝の優遇。2026年の方式に合わせ、10ゲーム差以上または対戦相手が勝率5割未満なら最大7試合・2勝の優遇になります。同勝数で終了が確定した場合は上位チームが勝ち上がります。日本シリーズは4勝先取、引き分け時は決着まで追加試合。雨天中止・予備日・実際の日付は簡略化しています。</p><a href="https://npb.jp/games/2026/info_cs.html" target="_blank" rel="noreferrer">2026年CSの公式開催方式 ↗</a></details>
 </section>;
}
function SeriesTile({series,club,name,onGame}:{series:PostSeries;club:string;name:(id:string)=>string;onGame:(g:GameResult)=>void}){
 return <article className={`series-tile ${[series.higher,series.lower].includes(club)?'my-series':''}`}><small>{series.league==='JAPAN'?'FINAL':series.league==='CENTRAL'?'CENTRAL':'PACIFIC'} · {stageLabel(series.stage)}</small><div className="series-score"><strong className={series.winner===series.higher?'winner':''}>{name(series.higher)}</strong><b>{series.wins[0]} <i>−</i> {series.wins[1]}</b><strong className={series.winner===series.lower?'winner':''}>{name(series.lower)}</strong></div><p>{series.winner?`${name(series.winner)} ${series.stage==='japan'?'日本一':'勝ち上がり'}`:`${series.target}勝先取${series.advantage?` · ${name(series.higher)}に${series.advantage}勝の優遇`:''}`}</p><div className="series-games">{series.results.map((game,i)=><button key={i} onClick={()=>onGame(game)} aria-label={`${stageLabel(series.stage)} ${name(game.home)}対${name(game.away)} 第${i+1}戦の結果`}><small>第{i+1}戦</small><b>{game.home===series.higher?game.homeRuns:game.awayRuns}–{game.home===series.higher?game.awayRuns:game.homeRuns}</b></button>)}</div></article>;
}
function SeasonReport({state,onPlayer}:{state:GameState;onPlayer:(p:Player)=>void}) {
 const s=state.season,bat=Object.values(s.batting).filter(b=>b.team===state.club),pit=Object.values(s.pitching).filter(p=>p.team===state.club);
 const bestBat=[...bat].filter(b=>b.pa>=s.day*3.1).sort((a,b)=>battingAverage(b)-battingAverage(a))[0],slugger=[...bat].sort((a,b)=>b.hr-a.hr)[0],ace=[...pit].filter(p=>p.outs>=s.day*3).sort((a,b)=>era(a)-era(b))[0];
 const leaders=[bestBat?{id:bestBat.playerId,label:'チーム最高打率',value:formatAvg(battingAverage(bestBat)),detail:`${bestBat.hits}安打 / ${bestBat.pa}打席`}:null,slugger?{id:slugger.playerId,label:'チーム最多本塁打',value:`${slugger.hr}本`,detail:`${slugger.rbi}打点 / ${slugger.runs}得点`}:null,ace?{id:ace.playerId,label:'チーム最優秀防御率',value:era(ace).toFixed(2),detail:`${ace.wins}勝 / ${formatIP(ace.outs)}回`}:null].filter(x=>x!==null);
 const postBat=Object.values(s.postseason?.batting??{}).filter(b=>b.team===state.club),postPit=Object.values(s.postseason?.pitching??{}).filter(p=>p.team===state.club);
 return <div className="season-report"><div className="eyebrow">YOUR SEASON, YOUR STARS</div><h3>143試合を彩った主役たち</h3><div className="season-leaders">{leaders.map(l=><button key={l.label} data-player-id={l.id} onClick={()=>onPlayer(playerMap[l.id])}><small>{l.label}</small><b>{l.value}</b><strong>{playerMap[l.id].name}</strong><span>{l.detail}</span></button>)}</div>{postBat.length>0&&<details className="post-stats"><summary>短期決戦の個人成績を見る</summary><div className="table-scroll"><table className="data-table"><thead><tr><th>野手</th><th>試合</th><th>打率</th><th>本塁打</th><th>打点</th><th>安打</th></tr></thead><tbody>{postBat.map(b=><tr key={b.playerId}><td><button data-player-id={b.playerId} onClick={()=>onPlayer(playerMap[b.playerId])}>{playerMap[b.playerId].name}</button></td><td>{b.games}</td><td>{formatAvg(battingAverage(b))}</td><td>{b.hr}</td><td>{b.rbi}</td><td>{b.hits}</td></tr>)}</tbody></table><table className="data-table"><thead><tr><th>投手</th><th>登板</th><th>防御率</th><th>勝</th><th>敗</th><th>セーブ</th><th>投球回</th></tr></thead><tbody>{postPit.map(p=><tr key={p.playerId}><td><button data-player-id={p.playerId} onClick={()=>onPlayer(playerMap[p.playerId])}>{playerMap[p.playerId].name}</button></td><td>{p.games}</td><td>{p.outs?era(p).toFixed(2):'—'}</td><td>{p.wins}</td><td>{p.losses}</td><td>{p.saves}</td><td>{formatIP(p.outs)}</td></tr>)}</tbody></table></div></details>}</div>;
}
